export const COUNTRIES = [
  { name: "Afghanistan", code: "AF", pop: 40218234, export: "Fruits & Nuts", flag: "🇦🇫", cont: "Asia" },
  { name: "Albania", code: "AL", pop: 2877797, export: "Textiles", flag: "🇦🇱", cont: "Europe" },
  { name: "Algeria", code: "DZ", pop: 44616624, export: "Petroleum", flag: "🇩🇿", cont: "Africa" },
  { name: "Andorra", code: "AD", pop: 77265, export: "Tobacco", flag: "🇦🇩", cont: "Europe" },
  { name: "Angola", code: "AO", pop: 34503774, export: "Crude Oil", flag: "🇦🇴", cont: "Africa" },
  { name: "Argentina", code: "AR", pop: 45376763, export: "Soybeans", flag: "🇦🇷", cont: "South America" },
  { name: "Armenia", code: "AM", pop: 2963234, export: "Copper", flag: "🇦🇲", cont: "Asia" },
  { name: "Australia", code: "AU", pop: 25978935, export: "Iron Ore", flag: "🇦🇺", cont: "Oceania" },
  { name: "Austria", code: "AT", pop: 9132383, export: "Machinery", flag: "🇦🇹", cont: "Europe" },
  { name: "Azerbaijan", code: "AZ", pop: 10282283, export: "Petroleum", flag: "🇦🇿", cont: "Asia" },
  { name: "Bahamas", code: "BS", pop: 393248, export: "Fish", flag: "🇧🇸", cont: "North America" },
  { name: "Bahrain", code: "BH", pop: 1463265, export: "Petroleum", flag: "🇧🇭", cont: "Asia" },
  { name: "Bangladesh", code: "BD", pop: 167885689, export: "Garments", flag: "🇧🇩", cont: "Asia" },
  { name: "Barbados", code: "BB", pop: 281635, export: "Sugar", flag: "🇧🇧", cont: "North America" },
  { name: "Belarus", code: "BY", pop: 9408350, export: "Machinery", flag: "🇧🇾", cont: "Europe" },
  { name: "Belgium", code: "BE", pop: 11632326, export: "Pharmaceuticals", flag: "🇧🇪", cont: "Europe" },
  { name: "Belize", code: "BZ", pop: 404914, export: "Sugar", flag: "🇧🇿", cont: "North America" },
  { name: "Benin", code: "BJ", pop: 12784264, export: "Cotton", flag: "🇧🇯", cont: "Africa" },
  { name: "Bhutan", code: "BT", pop: 771608, export: "Hydroelectricity", flag: "🇧🇹", cont: "Asia" },
  { name: "Bolivia", code: "BO", pop: 12079472, export: "Natural Gas", flag: "🇧🇴", cont: "South America" },
  { name: "Bosnia and Herzegovina", code: "BA", pop: 3280819, export: "Steel", flag: "🇧🇦", cont: "Europe" },
  { name: "Botswana", code: "BW", pop: 2630296, export: "Diamonds", flag: "🇧🇼", cont: "Africa" },
  { name: "Brazil", code: "BR", pop: 215313498, export: "Soybeans", flag: "🇧🇷", cont: "South America" },
  { name: "Brunei", code: "BN", pop: 441532, export: "Petroleum", flag: "🇧🇳", cont: "Asia" },
  { name: "Bulgaria", code: "BG", pop: 6519789, export: "Copper", flag: "🇧🇬", cont: "Europe" },
  { name: "Burkina Faso", code: "BF", pop: 22100683, export: "Cotton", flag: "🇧🇫", cont: "Africa" },
  { name: "Burundi", code: "BI", pop: 12889576, export: "Coffee", flag: "🇧🇮", cont: "Africa" },
  { name: "Cambodia", code: "KH", pop: 16718965, export: "Garments", flag: "🇰🇭", cont: "Asia" },
  { name: "Cameroon", code: "CM", pop: 27914536, export: "Crude Oil", flag: "🇨🇲", cont: "Africa" },
  { name: "Canada", code: "CA", pop: 38246108, export: "Petroleum", flag: "🇨🇦", cont: "North America" },
  { name: "Cape Verde", code: "CV", pop: 593149, export: "Fish", flag: "🇨🇻", cont: "Africa" },
  { name: "Central African Republic", code: "CF", pop: 4919981, export: "Timber", flag: "🇨🇫", cont: "Africa" },
  { name: "Chad", code: "TD", pop: 17413580, export: "Crude Oil", flag: "🇹🇩", cont: "Africa" },
  { name: "Chile", code: "CL", pop: 19212361, export: "Copper", flag: "🇨🇱", cont: "South America" },
  { name: "China", code: "CN", pop: 1412600000, export: "Electronics", flag: "🇨🇳", cont: "Asia" },
  { name: "Colombia", code: "CO", pop: 51874024, export: "Coffee", flag: "🇨🇴", cont: "South America" },
  { name: "Comoros", code: "KM", pop: 836774, export: "Vanilla", flag: "🇰🇲", cont: "Africa" },
  { name: "Congo", code: "CG", pop: 5797805, export: "Petroleum", flag: "🇨🇬", cont: "Africa" },
  { name: "Costa Rica", code: "CR", pop: 5153957, export: "Pineapples", flag: "🇨🇷", cont: "North America" },
  { name: "Croatia", code: "HR", pop: 4030358, export: "Machinery", flag: "🇭🇷", cont: "Europe" },
  { name: "Cuba", code: "CU", pop: 11212191, export: "Sugar", flag: "🇨🇺", cont: "North America" },
  { name: "Cyprus", code: "CY", pop: 1251488, export: "Pharmaceuticals", flag: "🇨🇾", cont: "Europe" },
  { name: "Czech Republic", code: "CZ", pop: 10900555, export: "Machinery", flag: "🇨🇿", cont: "Europe" },
  { name: "DR Congo", code: "CD", pop: 99010212, export: "Cobalt", flag: "🇨🇩", cont: "Africa" },
  { name: "Denmark", code: "DK", pop: 5873420, export: "Machinery", flag: "🇩🇰", cont: "Europe" },
  { name: "Djibouti", code: "DJ", pop: 1000543, export: "Re-exports", flag: "🇩🇯", cont: "Africa" },
  { name: "Dominican Republic", code: "DO", pop: 10953703, export: "Gold", flag: "🇩🇴", cont: "North America" },
  { name: "Ecuador", code: "EC", pop: 18001000, export: "Petroleum", flag: "🇪🇨", cont: "South America" },
  { name: "Egypt", code: "EG", pop: 104258327, export: "Petroleum", flag: "🇪🇬", cont: "Africa" },
  { name: "El Salvador", code: "SV", pop: 6336392, export: "Coffee", flag: "🇸🇻", cont: "North America" },
  { name: "Equatorial Guinea", code: "GQ", pop: 1496032, export: "Petroleum", flag: "🇬🇶", cont: "Africa" },
  { name: "Eritrea", code: "ER", pop: 3546421, export: "Gold", flag: "🇪🇷", cont: "Africa" },
  { name: "Estonia", code: "EE", pop: 1321910, export: "Machinery", flag: "🇪🇪", cont: "Europe" },
  { name: "Eswatini", code: "SZ", pop: 1172362, export: "Sugar", flag: "🇸🇿", cont: "Africa" },
  { name: "Ethiopia", code: "ET", pop: 120812698, export: "Coffee", flag: "🇪🇹", cont: "Africa" },
  { name: "Fiji", code: "FJ", pop: 929766, export: "Sugar", flag: "🇫🇯", cont: "Oceania" },
  { name: "Finland", code: "FI", pop: 5540745, export: "Machinery", flag: "🇫🇮", cont: "Europe" },
  { name: "France", code: "FR", pop: 67897000, export: "Aircraft", flag: "🇫🇷", cont: "Europe" },
  { name: "Gabon", code: "GA", pop: 2278825, export: "Petroleum", flag: "🇬🇦", cont: "Africa" },
  { name: "Gambia", code: "GM", pop: 2639916, export: "Peanuts", flag: "🇬🇲", cont: "Africa" },
  { name: "Georgia", code: "GE", pop: 3979765, export: "Copper", flag: "🇬🇪", cont: "Asia" },
  { name: "Germany", code: "DE", pop: 83369843, export: "Automobiles", flag: "🇩🇪", cont: "Europe" },
  { name: "Ghana", code: "GH", pop: 32395450, export: "Gold", flag: "🇬🇭", cont: "Africa" },
  { name: "Greece", code: "GR", pop: 10678632, export: "Petroleum", flag: "🇬🇷", cont: "Europe" },
  { name: "Guatemala", code: "GT", pop: 17109746, export: "Coffee", flag: "🇬🇹", cont: "North America" },
  { name: "Guinea", code: "GN", pop: 13531906, export: "Bauxite", flag: "🇬🇳", cont: "Africa" },
  { name: "Guinea-Bissau", code: "GW", pop: 2015494, export: "Cashews", flag: "🇬🇼", cont: "Africa" },
  { name: "Guyana", code: "GY", pop: 786559, export: "Petroleum", flag: "🇬🇾", cont: "South America" },
  { name: "Haiti", code: "HT", pop: 11447569, export: "Apparel", flag: "🇭🇹", cont: "North America" },
  { name: "Honduras", code: "HN", pop: 10278345, export: "Coffee", flag: "🇭🇳", cont: "North America" },
  { name: "Hungary", code: "HU", pop: 9710882, export: "Machinery", flag: "🇭🇺", cont: "Europe" },
  { name: "Iceland", code: "IS", pop: 372520, export: "Fish", flag: "🇮🇸", cont: "Europe" },
  { name: "India", code: "IN", pop: 1393409038, export: "Petroleum Products", flag: "🇮🇳", cont: "Asia" },
  { name: "Indonesia", code: "ID", pop: 273753191, export: "Coal", flag: "🇮🇩", cont: "Asia" },
  { name: "Iran", code: "IR", pop: 85028759, export: "Petroleum", flag: "🇮🇷", cont: "Asia" },
  { name: "Iraq", code: "IQ", pop: 41179350, export: "Petroleum", flag: "🇮🇶", cont: "Asia" },
  { name: "Ireland", code: "IE", pop: 5123536, export: "Pharmaceuticals", flag: "🇮🇪", cont: "Europe" },
  { name: "Israel", code: "IL", pop: 9364333, export: "Diamonds", flag: "🇮🇱", cont: "Asia" },
  { name: "Italy", code: "IT", pop: 59554023, export: "Machinery", flag: "🇮🇹", cont: "Europe" },
  { name: "Ivory Coast", code: "CI", pop: 27478249, export: "Cocoa", flag: "🇨🇮", cont: "Africa" },
  { name: "Jamaica", code: "JM", pop: 2827695, export: "Alumina", flag: "🇯🇲", cont: "North America" },
  { name: "Japan", code: "JP", pop: 125584838, export: "Automobiles", flag: "🇯🇵", cont: "Asia" },
  { name: "Jordan", code: "JO", pop: 10269021, export: "Phosphates", flag: "🇯🇴", cont: "Asia" },
  { name: "Kazakhstan", code: "KZ", pop: 18754440, export: "Petroleum", flag: "🇰🇿", cont: "Asia" },
  { name: "Kenya", code: "KE", pop: 54985698, export: "Tea", flag: "🇰🇪", cont: "Africa" },
  { name: "Kuwait", code: "KW", pop: 4270563, export: "Petroleum", flag: "🇰🇼", cont: "Asia" },
  { name: "Kyrgyzstan", code: "KG", pop: 6628356, export: "Gold", flag: "🇰🇬", cont: "Asia" },
  { name: "Laos", code: "LA", pop: 7379358, export: "Electricity", flag: "🇱🇦", cont: "Asia" },
  { name: "Latvia", code: "LV", pop: 1848837, export: "Timber", flag: "🇱🇻", cont: "Europe" },
  { name: "Lebanon", code: "LB", pop: 6769146, export: "Gold", flag: "🇱🇧", cont: "Asia" },
  { name: "Lesotho", code: "LS", pop: 2159812, export: "Diamonds", flag: "🇱🇸", cont: "Africa" },
  { name: "Liberia", code: "LR", pop: 5193416, export: "Iron Ore", flag: "🇱🇷", cont: "Africa" },
  { name: "Libya", code: "LY", pop: 6931067, export: "Petroleum", flag: "🇱🇾", cont: "Africa" },
  { name: "Liechtenstein", code: "LI", pop: 38387, export: "Machinery", flag: "🇱🇮", cont: "Europe" },
  { name: "Lithuania", code: "LT", pop: 2800138, export: "Petroleum", flag: "🇱🇹", cont: "Europe" },
  { name: "Luxembourg", code: "LU", pop: 640064, export: "Steel", flag: "🇱🇺", cont: "Europe" },
  { name: "Madagascar", code: "MG", pop: 27691018, export: "Vanilla", flag: "🇲🇬", cont: "Africa" },
  { name: "Malawi", code: "MW", pop: 19889742, export: "Tobacco", flag: "🇲🇼", cont: "Africa" },
  { name: "Malaysia", code: "MY", pop: 32776194, export: "Electronics", flag: "🇲🇾", cont: "Asia" },
  { name: "Maldives", code: "MV", pop: 543617, export: "Fish", flag: "🇲🇻", cont: "Asia" },
  { name: "Mali", code: "ML", pop: 22395489, export: "Gold", flag: "🇲🇱", cont: "Africa" },
  { name: "Malta", code: "MT", pop: 514564, export: "Machinery", flag: "🇲🇹", cont: "Europe" },
  { name: "Mauritania", code: "MR", pop: 4649658, export: "Iron Ore", flag: "🇲🇷", cont: "Africa" },
  { name: "Mauritius", code: "MU", pop: 1271768, export: "Sugar", flag: "🇲🇺", cont: "Africa" },
  { name: "Mexico", code: "MX", pop: 130262216, export: "Automobiles", flag: "🇲🇽", cont: "North America" },
  { name: "Moldova", code: "MD", pop: 2617820, export: "Wine", flag: "🇲🇩", cont: "Europe" },
  { name: "Monaco", code: "MC", pop: 36686, export: "Cosmetics", flag: "🇲🇨", cont: "Europe" },
  { name: "Mongolia", code: "MN", pop: 3347782, export: "Coal", flag: "🇲🇳", cont: "Asia" },
  { name: "Montenegro", code: "ME", pop: 621718, export: "Aluminum", flag: "🇲🇪", cont: "Europe" },
  { name: "Morocco", code: "MA", pop: 37457971, export: "Phosphates", flag: "🇲🇦", cont: "Africa" },
  { name: "Mozambique", code: "MZ", pop: 32790338, export: "Natural Gas", flag: "🇲🇿", cont: "Africa" },
  { name: "Myanmar", code: "MM", pop: 54409800, export: "Natural Gas", flag: "🇲🇲", cont: "Asia" },
  { name: "Namibia", code: "NA", pop: 2587344, export: "Diamonds", flag: "🇳🇦", cont: "Africa" },
  { name: "Nepal", code: "NP", pop: 29674920, export: "Carpets", flag: "🇳🇵", cont: "Asia" },
  { name: "Netherlands", code: "NL", pop: 17590672, export: "Machinery", flag: "🇳🇱", cont: "Europe" },
  { name: "New Zealand", code: "NZ", pop: 5123800, export: "Dairy", flag: "🇳🇿", cont: "Oceania" },
  { name: "Nicaragua", code: "NI", pop: 6779100, export: "Coffee", flag: "🇳🇮", cont: "North America" },
  { name: "Niger", code: "NE", pop: 25252722, export: "Uranium", flag: "🇳🇪", cont: "Africa" },
  { name: "Nigeria", code: "NG", pop: 213401323, export: "Petroleum", flag: "🇳🇬", cont: "Africa" },
  { name: "North Korea", code: "KP", pop: 25971909, export: "Coal", flag: "🇰🇵", cont: "Asia" },
  { name: "North Macedonia", code: "MK", pop: 2067172, export: "Steel", flag: "🇲🇰", cont: "Europe" },
  { name: "Norway", code: "NO", pop: 5408320, export: "Petroleum", flag: "🇳🇴", cont: "Europe" },
  { name: "Oman", code: "OM", pop: 4520471, export: "Petroleum", flag: "🇴🇲", cont: "Asia" },
  { name: "Pakistan", code: "PK", pop: 225199937, export: "Textiles", flag: "🇵🇰", cont: "Asia" },
  { name: "Panama", code: "PA", pop: 4351267, export: "Gold", flag: "🇵🇦", cont: "North America" },
  { name: "Papua New Guinea", code: "PG", pop: 9119000, export: "Petroleum", flag: "🇵🇬", cont: "Oceania" },
  { name: "Paraguay", code: "PY", pop: 7356413, export: "Soybeans", flag: "🇵🇾", cont: "South America" },
  { name: "Peru", code: "PE", pop: 32971854, export: "Copper", flag: "🇵🇪", cont: "South America" },
  { name: "Philippines", code: "PH", pop: 111046913, export: "Electronics", flag: "🇵🇭", cont: "Asia" },
  { name: "Poland", code: "PL", pop: 37840001, export: "Machinery", flag: "🇵🇱", cont: "Europe" },
  { name: "Portugal", code: "PT", pop: 10290103, export: "Automobiles", flag: "🇵🇹", cont: "Europe" },
  { name: "Qatar", code: "QA", pop: 2688235, export: "Natural Gas", flag: "🇶🇦", cont: "Asia" },
  { name: "Romania", code: "RO", pop: 19286123, export: "Machinery", flag: "🇷🇴", cont: "Europe" },
  { name: "Russia", code: "RU", pop: 145102755, export: "Petroleum", flag: "🇷🇺", cont: "Europe" },
  { name: "Rwanda", code: "RW", pop: 13461888, export: "Coffee", flag: "🇷🇼", cont: "Africa" },
  { name: "San Marino", code: "SM", pop: 34232, export: "Machinery", flag: "🇸🇲", cont: "Europe" },
  { name: "Saudi Arabia", code: "SA", pop: 35013414, export: "Petroleum", flag: "🇸🇦", cont: "Asia" },
  { name: "Senegal", code: "SN", pop: 17196301, export: "Fish", flag: "🇸🇳", cont: "Africa" },
  { name: "Serbia", code: "RS", pop: 6834326, export: "Automobiles", flag: "🇷🇸", cont: "Europe" },
  { name: "Sierra Leone", code: "SL", pop: 8420641, export: "Diamonds", flag: "🇸🇱", cont: "Africa" },
  { name: "Singapore", code: "SG", pop: 5896686, export: "Electronics", flag: "🇸🇬", cont: "Asia" },
  { name: "Slovakia", code: "SK", pop: 5460185, export: "Automobiles", flag: "🇸🇰", cont: "Europe" },
  { name: "Slovenia", code: "SI", pop: 2107180, export: "Machinery", flag: "🇸🇮", cont: "Europe" },
  { name: "Somalia", code: "SO", pop: 17065581, export: "Livestock", flag: "🇸🇴", cont: "Africa" },
  { name: "South Africa", code: "ZA", pop: 60041994, export: "Gold", flag: "🇿🇦", cont: "Africa" },
  { name: "South Korea", code: "KR", pop: 51744876, export: "Electronics", flag: "🇰🇷", cont: "Asia" },
  { name: "South Sudan", code: "SS", pop: 11193725, export: "Petroleum", flag: "🇸🇸", cont: "Africa" },
  { name: "Spain", code: "ES", pop: 47415750, export: "Automobiles", flag: "🇪🇸", cont: "Europe" },
  { name: "Sri Lanka", code: "LK", pop: 22156000, export: "Tea", flag: "🇱🇰", cont: "Asia" },
  { name: "Sudan", code: "SD", pop: 44909353, export: "Gold", flag: "🇸🇩", cont: "Africa" },
  { name: "Suriname", code: "SR", pop: 618040, export: "Gold", flag: "🇸🇷", cont: "South America" },
  { name: "Sweden", code: "SE", pop: 10379295, export: "Machinery", flag: "🇸🇪", cont: "Europe" },
  { name: "Switzerland", code: "CH", pop: 8636896, export: "Pharmaceuticals", flag: "🇨🇭", cont: "Europe" },
  { name: "Syria", code: "SY", pop: 21324367, export: "Petroleum", flag: "🇸🇾", cont: "Asia" },
  { name: "Taiwan", code: "TW", pop: 23570000, export: "Electronics", flag: "🇹🇼", cont: "Asia" },
  { name: "Tajikistan", code: "TJ", pop: 9900000, export: "Aluminum", flag: "🇹🇯", cont: "Asia" },
  { name: "Tanzania", code: "TZ", pop: 63298550, export: "Gold", flag: "🇹🇿", cont: "Africa" },
  { name: "Thailand", code: "TH", pop: 71601103, export: "Electronics", flag: "🇹🇭", cont: "Asia" },
  { name: "Timor-Leste", code: "TL", pop: 1318445, export: "Petroleum", flag: "🇹🇱", cont: "Asia" },
  { name: "Togo", code: "TG", pop: 8644829, export: "Phosphates", flag: "🇹🇬", cont: "Africa" },
  { name: "Trinidad and Tobago", code: "TT", pop: 1399488, export: "Petroleum", flag: "🇹🇹", cont: "North America" },
  { name: "Tunisia", code: "TN", pop: 11935766, export: "Petroleum", flag: "🇹🇳", cont: "Africa" },
  { name: "Turkey", code: "TR", pop: 84775404, export: "Automobiles", flag: "🇹🇷", cont: "Asia" },
  { name: "Turkmenistan", code: "TM", pop: 6117924, export: "Natural Gas", flag: "🇹🇲", cont: "Asia" },
  { name: "Uganda", code: "UG", pop: 47123531, export: "Coffee", flag: "🇺🇬", cont: "Africa" },
  { name: "Ukraine", code: "UA", pop: 43528136, export: "Iron & Steel", flag: "🇺🇦", cont: "Europe" },
  { name: "United Arab Emirates", code: "AE", pop: 9771000, export: "Petroleum", flag: "🇦🇪", cont: "Asia" },
  { name: "United Kingdom", code: "GB", pop: 67215293, export: "Machinery", flag: "🇬🇧", cont: "Europe" },
  { name: "United States", code: "US", pop: 331893745, export: "Petroleum Products", flag: "🇺🇸", cont: "North America" },
  { name: "Uruguay", code: "UY", pop: 3473730, export: "Soybeans", flag: "🇺🇾", cont: "South America" },
  { name: "Uzbekistan", code: "UZ", pop: 35300000, export: "Cotton", flag: "🇺🇿", cont: "Asia" },
  { name: "Venezuela", code: "VE", pop: 28301696, export: "Petroleum", flag: "🇻🇪", cont: "South America" },
  { name: "Vietnam", code: "VN", pop: 97338583, export: "Electronics", flag: "🇻🇳", cont: "Asia" },
  { name: "Yemen", code: "YE", pop: 33696614, export: "Petroleum", flag: "🇾🇪", cont: "Asia" },
  { name: "Zambia", code: "ZM", pop: 19470234, export: "Copper", flag: "🇿🇲", cont: "Africa" },
  { name: "Zimbabwe", code: "ZW", pop: 15178979, export: "Tobacco", flag: "🇿🇼", cont: "Africa" },
]

export const TOTAL = COUNTRIES.length
export const USERS = ["Mi", "Gary", "Hailey"]

export const COUNTRY_ALIASES = {
  "united states of america": "United States", "usa": "United States", "us": "United States", "america": "United States",
  "uk": "United Kingdom", "great britain": "United Kingdom", "england": "United Kingdom",
  "uae": "United Arab Emirates", "drc": "DR Congo", "democratic republic of congo": "DR Congo",
  "democratic republic of the congo": "DR Congo", "republic of the congo": "Congo",
  "czechia": "Czech Republic", "czech": "Czech Republic",
  "ivory coast": "Ivory Coast", "cote divoire": "Ivory Coast",
  "south korea": "South Korea", "republic of korea": "South Korea",
  "russia": "Russia", "russian federation": "Russia",
  "burma": "Myanmar", "swaziland": "Eswatini", "cabo verde": "Cape Verde",
  "timor leste": "Timor-Leste", "east timor": "Timor-Leste",
  "trinidad tobago": "Trinidad and Tobago", "bosnia": "Bosnia and Herzegovina",
  "north macedonia": "North Macedonia", "macedonia": "North Macedonia",
  "png": "Papua New Guinea",
}

const COUNTRY_MAP = {}
COUNTRIES.forEach(c => { COUNTRY_MAP[normalize(c.name)] = c.name })
const ALIAS_MAP = {}
Object.entries(COUNTRY_ALIASES).forEach(([k, v]) => { ALIAS_MAP[normalize(k)] = v })

export function normalize(s) {
  return s.toLowerCase().trim().replace(/[^a-z0-9 ]/g, "").replace(/\s+/g, " ")
}

export function resolveCountry(input) {
  const n = normalize(input)
  if (ALIAS_MAP[n]) return ALIAS_MAP[n]
  return COUNTRY_MAP[n] || null
}

export const CONT_COLORS = {
  "Africa": "#F59E0B", "Asia": "#EF4444", "Europe": "#3B82F6",
  "North America": "#10B981", "South America": "#8B5CF6", "Oceania": "#EC4899",
}

export const fmtPop = (n) => n >= 1e9 ? (n/1e9).toFixed(2)+"B" : n >= 1e6 ? (n/1e6).toFixed(1)+"M" : n >= 1e3 ? (n/1e3).toFixed(0)+"K" : n
export const fmtTime = (s) => { const m = Math.floor(s/60); return `${m}:${String(s%60).padStart(2,"0")}` }
