export const COUNTRIES = [
  { name: "Afghanistan", code: "AF", pop: 40200000, export: "Fruits & Nuts", flag: "🇦🇫", cont: "Asia", famous: "Khaled Hosseini" },
  { name: "Albania", code: "AL", pop: 2900000, export: "Textiles", flag: "🇦🇱", cont: "Europe", famous: "Mother Teresa" },
  { name: "Algeria", code: "DZ", pop: 44600000, export: "Petroleum", flag: "🇩🇿", cont: "Africa", famous: "Zinedine Zidane" },
  { name: "Andorra", code: "AD", pop: 77000, export: "Tobacco", flag: "🇦🇩", cont: "Europe", famous: "Joan Marti i Alanis" },
  { name: "Angola", code: "AO", pop: 34500000, export: "Crude Oil", flag: "🇦🇴", cont: "Africa", famous: "Jose Eduardo dos Santos" },
  { name: "Antigua and Barbuda", code: "AG", pop: 99000, export: "Petroleum Products", flag: "🇦🇬", cont: "North America", famous: "Viv Richards" },
  { name: "Argentina", code: "AR", pop: 45400000, export: "Soybeans", flag: "🇦🇷", cont: "South America", famous: "Lionel Messi" },
  { name: "Armenia", code: "AM", pop: 3000000, export: "Copper", flag: "🇦🇲", cont: "Asia", famous: "Aram Khachaturian" },
  { name: "Australia", code: "AU", pop: 26000000, export: "Iron Ore", flag: "🇦🇺", cont: "Oceania", famous: "Hugh Jackman" },
  { name: "Austria", code: "AT", pop: 9100000, export: "Machinery", flag: "🇦🇹", cont: "Europe", famous: "Wolfgang Amadeus Mozart" },
  { name: "Azerbaijan", code: "AZ", pop: 10300000, export: "Petroleum", flag: "🇦🇿", cont: "Asia", famous: "Garry Kasparov" },
  { name: "Bahamas", code: "BS", pop: 393000, export: "Fish", flag: "🇧🇸", cont: "North America", famous: "Sidney Poitier" },
  { name: "Bahrain", code: "BH", pop: 1500000, export: "Petroleum", flag: "🇧🇭", cont: "Asia", famous: "Hamad bin Isa Al Khalifa" },
  { name: "Bangladesh", code: "BD", pop: 167900000, export: "Garments", flag: "🇧🇩", cont: "Asia", famous: "Muhammad Yunus" },
  { name: "Barbados", code: "BB", pop: 282000, export: "Sugar", flag: "🇧🇧", cont: "North America", famous: "Rihanna" },
  { name: "Belarus", code: "BY", pop: 9400000, export: "Machinery", flag: "🇧🇾", cont: "Europe", famous: "Victoria Azarenka" },
  { name: "Belgium", code: "BE", pop: 11600000, export: "Pharmaceuticals", flag: "🇧🇪", cont: "Europe", famous: "Rene Magritte" },
  { name: "Belize", code: "BZ", pop: 405000, export: "Sugar", flag: "🇧🇿", cont: "North America", famous: "George Cadle Price" },
  { name: "Benin", code: "BJ", pop: 12800000, export: "Cotton", flag: "🇧🇯", cont: "Africa", famous: "Angelique Kidjo" },
  { name: "Bhutan", code: "BT", pop: 772000, export: "Hydroelectricity", flag: "🇧🇹", cont: "Asia", famous: "Jigme Khesar Namgyel Wangchuck" },
  { name: "Bolivia", code: "BO", pop: 12100000, export: "Natural Gas", flag: "🇧🇴", cont: "South America", famous: "Evo Morales" },
  { name: "Bosnia and Herzegovina", code: "BA", pop: 3300000, export: "Steel", flag: "🇧🇦", cont: "Europe", famous: "Edin Dzeko" },
  { name: "Botswana", code: "BW", pop: 2600000, export: "Diamonds", flag: "🇧🇼", cont: "Africa", famous: "Mpule Kwelagobe" },
  { name: "Brazil", code: "BR", pop: 215300000, export: "Soybeans", flag: "🇧🇷", cont: "South America", famous: "Pele" },
  { name: "Brunei", code: "BN", pop: 442000, export: "Petroleum", flag: "🇧🇳", cont: "Asia", famous: "Hassanal Bolkiah" },
  { name: "Bulgaria", code: "BG", pop: 6500000, export: "Copper", flag: "🇧🇬", cont: "Europe", famous: "Hristo Stoichkov" },
  { name: "Burkina Faso", code: "BF", pop: 22100000, export: "Cotton", flag: "🇧🇫", cont: "Africa", famous: "Thomas Sankara" },
  { name: "Burundi", code: "BI", pop: 12900000, export: "Coffee", flag: "🇧🇮", cont: "Africa", famous: "Pierre Nkurunziza" },
  { name: "Cambodia", code: "KH", pop: 16700000, export: "Garments", flag: "🇰🇭", cont: "Asia", famous: "Norodom Sihanouk" },
  { name: "Cameroon", code: "CM", pop: 27900000, export: "Crude Oil", flag: "🇨🇲", cont: "Africa", famous: "Samuel Etoo" },
  { name: "Canada", code: "CA", pop: 38200000, export: "Petroleum", flag: "🇨🇦", cont: "North America", famous: "Terry Fox" },
  { name: "Cape Verde", code: "CV", pop: 593000, export: "Fish", flag: "🇨🇻", cont: "Africa", famous: "Cesaria Evora" },
  { name: "Central African Republic", code: "CF", pop: 4900000, export: "Timber", flag: "🇨🇫", cont: "Africa", famous: "Barthelemy Boganda" },
  { name: "Chad", code: "TD", pop: 17400000, export: "Crude Oil", flag: "🇹🇩", cont: "Africa", famous: "Idriss Deby" },
  { name: "Chile", code: "CL", pop: 19200000, export: "Copper", flag: "🇨🇱", cont: "South America", famous: "Pablo Neruda" },
  { name: "China", code: "CN", pop: 1410000000, export: "Electronics", flag: "🇨🇳", cont: "Asia", famous: "Confucius" },
  { name: "Colombia", code: "CO", pop: 51900000, export: "Coffee", flag: "🇨🇴", cont: "South America", famous: "Gabriel Garcia Marquez" },
  { name: "Comoros", code: "KM", pop: 837000, export: "Vanilla", flag: "🇰🇲", cont: "Africa", famous: "Azali Assoumani" },
  { name: "Congo", code: "CG", pop: 5800000, export: "Petroleum", flag: "🇨🇬", cont: "Africa", famous: "Denis Sassou Nguesso" },
  { name: "Costa Rica", code: "CR", pop: 5200000, export: "Pineapples", flag: "🇨🇷", cont: "North America", famous: "Oscar Arias" },
  { name: "Croatia", code: "HR", pop: 4000000, export: "Machinery", flag: "🇭🇷", cont: "Europe", famous: "Nikola Tesla" },
  { name: "Cuba", code: "CU", pop: 11200000, export: "Sugar", flag: "🇨🇺", cont: "North America", famous: "Fidel Castro" },
  { name: "Cyprus", code: "CY", pop: 1300000, export: "Pharmaceuticals", flag: "🇨🇾", cont: "Europe", famous: "Archbishop Makarios III" },
  { name: "Czech Republic", code: "CZ", pop: 10900000, export: "Machinery", flag: "🇨🇿", cont: "Europe", famous: "Franz Kafka" },
  { name: "Denmark", code: "DK", pop: 5900000, export: "Machinery", flag: "🇩🇰", cont: "Europe", famous: "Hans Christian Andersen" },
  { name: "Djibouti", code: "DJ", pop: 1000000, export: "Re-exports", flag: "🇩🇯", cont: "Africa", famous: "Ismail Omar Guelleh" },
  { name: "Dominica", code: "DM", pop: 72000, export: "Bananas", flag: "🇩🇲", cont: "North America", famous: "Jean Rhys" },
  { name: "Dominican Republic", code: "DO", pop: 11000000, export: "Gold", flag: "🇩🇴", cont: "North America", famous: "Juan Luis Guerra" },
  { name: "DR Congo", code: "CD", pop: 99000000, export: "Cobalt", flag: "🇨🇩", cont: "Africa", famous: "Patrice Lumumba" },
  { name: "Ecuador", code: "EC", pop: 18000000, export: "Petroleum", flag: "🇪🇨", cont: "South America", famous: "Richard Carapaz" },
  { name: "Egypt", code: "EG", pop: 104300000, export: "Petroleum", flag: "🇪🇬", cont: "Africa", famous: "Mohamed Salah" },
  { name: "El Salvador", code: "SV", pop: 6300000, export: "Coffee", flag: "🇸🇻", cont: "North America", famous: "Oscar Romero" },
  { name: "Equatorial Guinea", code: "GQ", pop: 1500000, export: "Petroleum", flag: "🇬🇶", cont: "Africa", famous: "Teodoro Obiang" },
  { name: "Eritrea", code: "ER", pop: 3500000, export: "Gold", flag: "🇪🇷", cont: "Africa", famous: "Isaias Afwerki" },
  { name: "Estonia", code: "EE", pop: 1300000, export: "Machinery", flag: "🇪🇪", cont: "Europe", famous: "Arvo Part" },
  { name: "Eswatini", code: "SZ", pop: 1200000, export: "Sugar", flag: "🇸🇿", cont: "Africa", famous: "King Mswati III" },
  { name: "Ethiopia", code: "ET", pop: 120800000, export: "Coffee", flag: "🇪🇹", cont: "Africa", famous: "Haile Selassie" },
  { name: "Fiji", code: "FJ", pop: 930000, export: "Sugar", flag: "🇫🇯", cont: "Oceania", famous: "Vijay Singh" },
  { name: "Finland", code: "FI", pop: 5500000, export: "Machinery", flag: "🇫🇮", cont: "Europe", famous: "Jean Sibelius" },
  { name: "France", code: "FR", pop: 67900000, export: "Aircraft", flag: "🇫🇷", cont: "Europe", famous: "Napoleon Bonaparte" },
  { name: "Gabon", code: "GA", pop: 2300000, export: "Petroleum", flag: "🇬🇦", cont: "Africa", famous: "Pierre-Emerick Aubameyang" },
  { name: "Gambia", code: "GM", pop: 2600000, export: "Peanuts", flag: "🇬🇲", cont: "Africa", famous: "Dawda Jawara" },
  { name: "Georgia", code: "GE", pop: 4000000, export: "Copper", flag: "🇬🇪", cont: "Asia", famous: "Joseph Stalin" },
  { name: "Germany", code: "DE", pop: 83400000, export: "Automobiles", flag: "🇩🇪", cont: "Europe", famous: "Albert Einstein" },
  { name: "Ghana", code: "GH", pop: 32400000, export: "Gold", flag: "🇬🇭", cont: "Africa", famous: "Kofi Annan" },
  { name: "Greece", code: "GR", pop: 10700000, export: "Petroleum", flag: "🇬🇷", cont: "Europe", famous: "Aristotle" },
  { name: "Grenada", code: "GD", pop: 113000, export: "Nutmeg", flag: "🇬🇩", cont: "North America", famous: "Maurice Bishop" },
  { name: "Guatemala", code: "GT", pop: 17100000, export: "Coffee", flag: "🇬🇹", cont: "North America", famous: "Rigoberta Menchu" },
  { name: "Guinea", code: "GN", pop: 13500000, export: "Bauxite", flag: "🇬🇳", cont: "Africa", famous: "Ahmed Sekou Toure" },
  { name: "Guinea-Bissau", code: "GW", pop: 2000000, export: "Cashews", flag: "🇬🇼", cont: "Africa", famous: "Amilcar Cabral" },
  { name: "Guyana", code: "GY", pop: 787000, export: "Petroleum", flag: "🇬🇾", cont: "South America", famous: "Walter Rodney" },
  { name: "Haiti", code: "HT", pop: 11400000, export: "Apparel", flag: "🇭🇹", cont: "North America", famous: "Toussaint Louverture" },
  { name: "Vatican City", code: "VA", pop: 800, export: "Cultural Services", flag: "🇻🇦", cont: "Europe", famous: "Pope Francis" },
  { name: "Honduras", code: "HN", pop: 10300000, export: "Coffee", flag: "🇭🇳", cont: "North America", famous: "Berta Caceres" },
  { name: "Hungary", code: "HU", pop: 9700000, export: "Machinery", flag: "🇭🇺", cont: "Europe", famous: "Erno Rubik" },
  { name: "Iceland", code: "IS", pop: 373000, export: "Fish", flag: "🇮🇸", cont: "Europe", famous: "Bjork" },
  { name: "India", code: "IN", pop: 1390000000, export: "Petroleum Products", flag: "🇮🇳", cont: "Asia", famous: "Mahatma Gandhi" },
  { name: "Indonesia", code: "ID", pop: 273800000, export: "Coal", flag: "🇮🇩", cont: "Asia", famous: "Sukarno" },
  { name: "Iran", code: "IR", pop: 85000000, export: "Petroleum", flag: "🇮🇷", cont: "Asia", famous: "Cyrus the Great" },
  { name: "Iraq", code: "IQ", pop: 41200000, export: "Petroleum", flag: "🇮🇶", cont: "Asia", famous: "Zaha Hadid" },
  { name: "Ireland", code: "IE", pop: 5100000, export: "Pharmaceuticals", flag: "🇮🇪", cont: "Europe", famous: "Oscar Wilde" },
  { name: "Israel", code: "IL", pop: 9400000, export: "Diamonds", flag: "🇮🇱", cont: "Asia", famous: "Golda Meir" },
  { name: "Italy", code: "IT", pop: 59600000, export: "Machinery", flag: "🇮🇹", cont: "Europe", famous: "Leonardo da Vinci" },
  { name: "Ivory Coast", code: "CI", pop: 27500000, export: "Cocoa", flag: "🇨🇮", cont: "Africa", famous: "Didier Drogba" },
  { name: "Jamaica", code: "JM", pop: 2800000, export: "Alumina", flag: "🇯🇲", cont: "North America", famous: "Bob Marley" },
  { name: "Japan", code: "JP", pop: 125600000, export: "Automobiles", flag: "🇯🇵", cont: "Asia", famous: "Akira Kurosawa" },
  { name: "Jordan", code: "JO", pop: 10300000, export: "Phosphates", flag: "🇯🇴", cont: "Asia", famous: "Queen Rania" },
  { name: "Kazakhstan", code: "KZ", pop: 18800000, export: "Petroleum", flag: "🇰🇿", cont: "Asia", famous: "Nursultan Nazarbayev" },
  { name: "Kenya", code: "KE", pop: 55000000, export: "Tea", flag: "🇰🇪", cont: "Africa", famous: "Jomo Kenyatta" },
  { name: "Kiribati", code: "KI", pop: 121000, export: "Fish", flag: "🇰🇮", cont: "Oceania", famous: "Anote Tong" },
  { name: "Kuwait", code: "KW", pop: 4300000, export: "Petroleum", flag: "🇰🇼", cont: "Asia", famous: "Sabah Al-Ahmad Al-Jaber Al-Sabah" },
  { name: "Kyrgyzstan", code: "KG", pop: 6600000, export: "Gold", flag: "🇰🇬", cont: "Asia", famous: "Chingiz Aitmatov" },
  { name: "Laos", code: "LA", pop: 7400000, export: "Electricity", flag: "🇱🇦", cont: "Asia", famous: "Kaysone Phomvihane" },
  { name: "Latvia", code: "LV", pop: 1800000, export: "Timber", flag: "🇱🇻", cont: "Europe", famous: "Mikhail Baryshnikov" },
  { name: "Lebanon", code: "LB", pop: 6800000, export: "Gold", flag: "🇱🇧", cont: "Asia", famous: "Khalil Gibran" },
  { name: "Lesotho", code: "LS", pop: 2200000, export: "Diamonds", flag: "🇱🇸", cont: "Africa", famous: "King Letsie III" },
  { name: "Liberia", code: "LR", pop: 5200000, export: "Iron Ore", flag: "🇱🇷", cont: "Africa", famous: "Ellen Johnson Sirleaf" },
  { name: "Libya", code: "LY", pop: 6900000, export: "Petroleum", flag: "🇱🇾", cont: "Africa", famous: "Muammar Gaddafi" },
  { name: "Liechtenstein", code: "LI", pop: 38000, export: "Machinery", flag: "🇱🇮", cont: "Europe", famous: "Hans-Adam II" },
  { name: "Lithuania", code: "LT", pop: 2800000, export: "Petroleum", flag: "🇱🇹", cont: "Europe", famous: "Arvydas Sabonis" },
  { name: "Luxembourg", code: "LU", pop: 640000, export: "Steel", flag: "🇱🇺", cont: "Europe", famous: "Jean-Claude Juncker" },
  { name: "Madagascar", code: "MG", pop: 27700000, export: "Vanilla", flag: "🇲🇬", cont: "Africa", famous: "Ranavalona I" },
  { name: "Malawi", code: "MW", pop: 19900000, export: "Tobacco", flag: "🇲🇼", cont: "Africa", famous: "Hastings Banda" },
  { name: "Malaysia", code: "MY", pop: 32800000, export: "Electronics", flag: "🇲🇾", cont: "Asia", famous: "Michelle Yeoh" },
  { name: "Maldives", code: "MV", pop: 544000, export: "Fish", flag: "🇲🇻", cont: "Asia", famous: "Maumoon Abdul Gayoom" },
  { name: "Mali", code: "ML", pop: 22400000, export: "Gold", flag: "🇲🇱", cont: "Africa", famous: "Mansa Musa" },
  { name: "Malta", code: "MT", pop: 515000, export: "Machinery", flag: "🇲🇹", cont: "Europe", famous: "Joseph Muscat" },
  { name: "Marshall Islands", code: "MH", pop: 59000, export: "Fish", flag: "🇲🇭", cont: "Oceania", famous: "Hilda Heine" },
  { name: "Mauritania", code: "MR", pop: 4600000, export: "Iron Ore", flag: "🇲🇷", cont: "Africa", famous: "Moktar Ould Daddah" },
  { name: "Mauritius", code: "MU", pop: 1300000, export: "Sugar", flag: "🇲🇺", cont: "Africa", famous: "Seewoosagur Ramgoolam" },
  { name: "Mexico", code: "MX", pop: 130300000, export: "Automobiles", flag: "🇲🇽", cont: "North America", famous: "Frida Kahlo" },
  { name: "Micronesia", code: "FM", pop: 116000, export: "Fish", flag: "🇫🇲", cont: "Oceania", famous: "Peter Christian" },
  { name: "Moldova", code: "MD", pop: 2600000, export: "Wine", flag: "🇲🇩", cont: "Europe", famous: "Maia Sandu" },
  { name: "Monaco", code: "MC", pop: 37000, export: "Cosmetics", flag: "🇲🇨", cont: "Europe", famous: "Grace Kelly" },
  { name: "Mongolia", code: "MN", pop: 3300000, export: "Coal", flag: "🇲🇳", cont: "Asia", famous: "Genghis Khan" },
  { name: "Montenegro", code: "ME", pop: 622000, export: "Aluminum", flag: "🇲🇪", cont: "Europe", famous: "Petar II Petrovic-Njegos" },
  { name: "Morocco", code: "MA", pop: 37500000, export: "Phosphates", flag: "🇲🇦", cont: "Africa", famous: "Ibn Battuta" },
  { name: "Mozambique", code: "MZ", pop: 32800000, export: "Natural Gas", flag: "🇲🇿", cont: "Africa", famous: "Samora Machel" },
  { name: "Myanmar", code: "MM", pop: 54400000, export: "Natural Gas", flag: "🇲🇲", cont: "Asia", famous: "Aung San Suu Kyi" },
  { name: "Namibia", code: "NA", pop: 2600000, export: "Diamonds", flag: "🇳🇦", cont: "Africa", famous: "Sam Nujoma" },
  { name: "Nauru", code: "NR", pop: 10000, export: "Phosphates", flag: "🇳🇷", cont: "Oceania", famous: "Baron Waqa" },
  { name: "Nepal", code: "NP", pop: 29700000, export: "Carpets", flag: "🇳🇵", cont: "Asia", famous: "Tenzing Norgay" },
  { name: "Netherlands", code: "NL", pop: 17600000, export: "Machinery", flag: "🇳🇱", cont: "Europe", famous: "Vincent van Gogh" },
  { name: "New Zealand", code: "NZ", pop: 5100000, export: "Dairy", flag: "🇳🇿", cont: "Oceania", famous: "Lorde" },
  { name: "Nicaragua", code: "NI", pop: 6800000, export: "Coffee", flag: "🇳🇮", cont: "North America", famous: "Ruben Dario" },
  { name: "Niger", code: "NE", pop: 25300000, export: "Uranium", flag: "🇳🇪", cont: "Africa", famous: "Hamani Diori" },
  { name: "Nigeria", code: "NG", pop: 213400000, export: "Petroleum", flag: "🇳🇬", cont: "Africa", famous: "Chinua Achebe" },
  { name: "North Korea", code: "KP", pop: 26000000, export: "Coal", flag: "🇰🇵", cont: "Asia", famous: "Kim Jong Un" },
  { name: "North Macedonia", code: "MK", pop: 2100000, export: "Steel", flag: "🇲🇰", cont: "Europe", famous: "Alexander the Great" },
  { name: "Norway", code: "NO", pop: 5400000, export: "Petroleum", flag: "🇳🇴", cont: "Europe", famous: "Edvard Munch" },
  { name: "Oman", code: "OM", pop: 4500000, export: "Petroleum", flag: "🇴🇲", cont: "Asia", famous: "Qaboos bin Said" },
  { name: "Pakistan", code: "PK", pop: 225200000, export: "Textiles", flag: "🇵🇰", cont: "Asia", famous: "Malala Yousafzai" },
  { name: "Palau", code: "PW", pop: 18000, export: "Fish", flag: "🇵🇼", cont: "Oceania", famous: "Tommy Remengesau" },
  { name: "Panama", code: "PA", pop: 4400000, export: "Gold", flag: "🇵🇦", cont: "North America", famous: "Mariano Rivera" },
  { name: "Papua New Guinea", code: "PG", pop: 9100000, export: "Petroleum", flag: "🇵🇬", cont: "Oceania", famous: "Michael Somare" },
  { name: "Paraguay", code: "PY", pop: 7400000, export: "Soybeans", flag: "🇵🇾", cont: "South America", famous: "Augusto Roa Bastos" },
  { name: "Peru", code: "PE", pop: 33000000, export: "Copper", flag: "🇵🇪", cont: "South America", famous: "Mario Vargas Llosa" },
  { name: "Philippines", code: "PH", pop: 111000000, export: "Electronics", flag: "🇵🇭", cont: "Asia", famous: "Manny Pacquiao" },
  { name: "Poland", code: "PL", pop: 37800000, export: "Machinery", flag: "🇵🇱", cont: "Europe", famous: "Marie Curie" },
  { name: "Portugal", code: "PT", pop: 10300000, export: "Automobiles", flag: "🇵🇹", cont: "Europe", famous: "Cristiano Ronaldo" },
  { name: "Qatar", code: "QA", pop: 2700000, export: "Natural Gas", flag: "🇶🇦", cont: "Asia", famous: "Tamim bin Hamad Al Thani" },
  { name: "Romania", code: "RO", pop: 19300000, export: "Machinery", flag: "🇷🇴", cont: "Europe", famous: "Nadia Comaneci" },
  { name: "Russia", code: "RU", pop: 145100000, export: "Petroleum", flag: "🇷🇺", cont: "Europe", famous: "Fyodor Dostoevsky" },
  { name: "Rwanda", code: "RW", pop: 13500000, export: "Coffee", flag: "🇷🇼", cont: "Africa", famous: "Paul Kagame" },
  { name: "Saint Kitts and Nevis", code: "KN", pop: 53000, export: "Electronics", flag: "🇰🇳", cont: "North America", famous: "Alexander Hamilton" },
  { name: "Saint Lucia", code: "LC", pop: 184000, export: "Bananas", flag: "🇱🇨", cont: "North America", famous: "Derek Walcott" },
  { name: "Saint Vincent and the Grenadines", code: "VC", pop: 111000, export: "Bananas", flag: "🇻🇨", cont: "North America", famous: "Ralph Gonsalves" },
  { name: "Samoa", code: "WS", pop: 200000, export: "Insulated Wire", flag: "🇼🇸", cont: "Oceania", famous: "Dwayne Johnson" },
  { name: "San Marino", code: "SM", pop: 34000, export: "Machinery", flag: "🇸🇲", cont: "Europe", famous: "Saint Marinus" },
  { name: "Sao Tome and Principe", code: "ST", pop: 223000, export: "Cocoa", flag: "🇸🇹", cont: "Africa", famous: "Manuel Pinto da Costa" },
  { name: "Saudi Arabia", code: "SA", pop: 35000000, export: "Petroleum", flag: "🇸🇦", cont: "Asia", famous: "Mohammed bin Salman" },
  { name: "Senegal", code: "SN", pop: 17200000, export: "Fish", flag: "🇸🇳", cont: "Africa", famous: "Sadio Mane" },
  { name: "Serbia", code: "RS", pop: 6800000, export: "Automobiles", flag: "🇷🇸", cont: "Europe", famous: "Novak Djokovic" },
  { name: "Seychelles", code: "SC", pop: 99000, export: "Canned Fish", flag: "🇸🇨", cont: "Africa", famous: "James Michel" },
  { name: "Sierra Leone", code: "SL", pop: 8400000, export: "Diamonds", flag: "🇸🇱", cont: "Africa", famous: "Ahmad Tejan Kabbah" },
  { name: "Singapore", code: "SG", pop: 5900000, export: "Electronics", flag: "🇸🇬", cont: "Asia", famous: "Lee Kuan Yew" },
  { name: "Slovakia", code: "SK", pop: 5500000, export: "Automobiles", flag: "🇸🇰", cont: "Europe", famous: "Peter Sagan" },
  { name: "Slovenia", code: "SI", pop: 2100000, export: "Machinery", flag: "🇸🇮", cont: "Europe", famous: "Luka Doncic" },
  { name: "Solomon Islands", code: "SB", pop: 703000, export: "Timber", flag: "🇸🇧", cont: "Oceania", famous: "Manasseh Sogavare" },
  { name: "Somalia", code: "SO", pop: 17100000, export: "Livestock", flag: "🇸🇴", cont: "Africa", famous: "Iman" },
  { name: "South Africa", code: "ZA", pop: 60000000, export: "Gold", flag: "🇿🇦", cont: "Africa", famous: "Nelson Mandela" },
  { name: "South Korea", code: "KR", pop: 51700000, export: "Electronics", flag: "🇰🇷", cont: "Asia", famous: "BTS" },
  { name: "South Sudan", code: "SS", pop: 11200000, export: "Petroleum", flag: "🇸🇸", cont: "Africa", famous: "Alek Wek" },
  { name: "Spain", code: "ES", pop: 47400000, export: "Automobiles", flag: "🇪🇸", cont: "Europe", famous: "Pablo Picasso" },
  { name: "Sri Lanka", code: "LK", pop: 22200000, export: "Tea", flag: "🇱🇰", cont: "Asia", famous: "Arthur C. Clarke" },
  { name: "State of Palestine", code: "PS", pop: 5200000, export: "Stone", flag: "🇵🇸", cont: "Asia", famous: "Mahmoud Darwish" },
  { name: "Sudan", code: "SD", pop: 44900000, export: "Gold", flag: "🇸🇩", cont: "Africa", famous: "Al-Mahdi" },
  { name: "Suriname", code: "SR", pop: 618000, export: "Gold", flag: "🇸🇷", cont: "South America", famous: "Desi Bouterse" },
  { name: "Sweden", code: "SE", pop: 10400000, export: "Machinery", flag: "🇸🇪", cont: "Europe", famous: "ABBA" },
  { name: "Switzerland", code: "CH", pop: 8600000, export: "Pharmaceuticals", flag: "🇨🇭", cont: "Europe", famous: "Roger Federer" },
  { name: "Syria", code: "SY", pop: 21300000, export: "Petroleum", flag: "🇸🇾", cont: "Asia", famous: "Nizar Qabbani" },
  { name: "Taiwan", code: "TW", pop: 23600000, export: "Electronics", flag: "🇹🇼", cont: "Asia", famous: "Ang Lee" },
  { name: "Tajikistan", code: "TJ", pop: 9900000, export: "Aluminum", flag: "🇹🇯", cont: "Asia", famous: "Emomali Rahmon" },
  { name: "Tanzania", code: "TZ", pop: 63300000, export: "Gold", flag: "🇹🇿", cont: "Africa", famous: "Julius Nyerere" },
  { name: "Thailand", code: "TH", pop: 71600000, export: "Electronics", flag: "🇹🇭", cont: "Asia", famous: "Lalisa Manobal" },
  { name: "Timor-Leste", code: "TL", pop: 1300000, export: "Petroleum", flag: "🇹🇱", cont: "Asia", famous: "Jose Ramos-Horta" },
  { name: "Togo", code: "TG", pop: 8600000, export: "Phosphates", flag: "🇹🇬", cont: "Africa", famous: "Emmanuel Adebayor" },
  { name: "Tonga", code: "TO", pop: 106000, export: "Squash", flag: "🇹🇴", cont: "Oceania", famous: "Pita Taufatofua" },
  { name: "Trinidad and Tobago", code: "TT", pop: 1400000, export: "Petroleum", flag: "🇹🇹", cont: "North America", famous: "Nicki Minaj" },
  { name: "Tunisia", code: "TN", pop: 11900000, export: "Petroleum", flag: "🇹🇳", cont: "Africa", famous: "Hannibal Barca" },
  { name: "Turkey", code: "TR", pop: 84800000, export: "Automobiles", flag: "🇹🇷", cont: "Asia", famous: "Mustafa Kemal Ataturk" },
  { name: "Turkmenistan", code: "TM", pop: 6100000, export: "Natural Gas", flag: "🇹🇲", cont: "Asia", famous: "Gurbanguly Berdimuhamedow" },
  { name: "Tuvalu", code: "TV", pop: 11000, export: "Fish", flag: "🇹🇻", cont: "Oceania", famous: "Kausea Natano" },
  { name: "Uganda", code: "UG", pop: 47100000, export: "Coffee", flag: "🇺🇬", cont: "Africa", famous: "Idi Amin" },
  { name: "Ukraine", code: "UA", pop: 43500000, export: "Iron & Steel", flag: "🇺🇦", cont: "Europe", famous: "Volodymyr Zelenskyy" },
  { name: "United Arab Emirates", code: "AE", pop: 9800000, export: "Petroleum", flag: "🇦🇪", cont: "Asia", famous: "Zayed bin Sultan Al Nahyan" },
  { name: "United Kingdom", code: "GB", pop: 67200000, export: "Machinery", flag: "🇬🇧", cont: "Europe", famous: "William Shakespeare" },
  { name: "United States", code: "US", pop: 331900000, export: "Petroleum Products", flag: "🇺🇸", cont: "North America", famous: "George Washington" },
  { name: "Uruguay", code: "UY", pop: 3500000, export: "Soybeans", flag: "🇺🇾", cont: "South America", famous: "Luis Suarez" },
  { name: "Uzbekistan", code: "UZ", pop: 35300000, export: "Cotton", flag: "🇺🇿", cont: "Asia", famous: "Timur (Tamerlane)" },
  { name: "Vanuatu", code: "VU", pop: 314000, export: "Copra", flag: "🇻🇺", cont: "Oceania", famous: "Edward Natapei" },
  { name: "Venezuela", code: "VE", pop: 28300000, export: "Petroleum", flag: "🇻🇪", cont: "South America", famous: "Simon Bolivar" },
  { name: "Vietnam", code: "VN", pop: 97300000, export: "Electronics", flag: "🇻🇳", cont: "Asia", famous: "Ho Chi Minh" },
  { name: "Yemen", code: "YE", pop: 33700000, export: "Petroleum", flag: "🇾🇪", cont: "Asia", famous: "Tawakkol Karman" },
  { name: "Zambia", code: "ZM", pop: 19500000, export: "Copper", flag: "🇿🇲", cont: "Africa", famous: "Kenneth Kaunda" },
  { name: "Zimbabwe", code: "ZW", pop: 15200000, export: "Tobacco", flag: "🇿🇼", cont: "Africa", famous: "Robert Mugabe" },
]
export const TOTAL = COUNTRIES.length
export const USERS = ["Mi", "Gary", "Hailey"]
export const COUNTRY_ALIASES = {
  "usa": "United States", "us": "United States", "america": "United States", "united states of america": "United States",
  "uk": "United Kingdom", "great britain": "United Kingdom", "england": "United Kingdom",
  "uae": "United Arab Emirates",
  "drc": "DR Congo", "democratic republic of congo": "DR Congo", "democratic republic of the congo": "DR Congo",
  "republic of the congo": "Congo",
  "czechia": "Czech Republic", "czech": "Czech Republic",
  "ivory coast": "Ivory Coast", "cote divoire": "Ivory Coast", "cote d ivoire": "Ivory Coast",
  "south korea": "South Korea", "republic of korea": "South Korea", "korea": "South Korea",
  "russia": "Russia", "russian federation": "Russia",
  "burma": "Myanmar", "swaziland": "Eswatini", "cabo verde": "Cape Verde",
  "timor leste": "Timor-Leste", "east timor": "Timor-Leste",
  "trinidad tobago": "Trinidad and Tobago", "trinidad": "Trinidad and Tobago",
  "bosnia": "Bosnia and Herzegovina", "herzegovina": "Bosnia and Herzegovina",
  "north macedonia": "North Macedonia", "macedonia": "North Macedonia",
  "png": "Papua New Guinea",
  "saint vincent": "Saint Vincent and the Grenadines", "st vincent": "Saint Vincent and the Grenadines", "st vincent and the grenadines": "Saint Vincent and the Grenadines",
  "saint kitts": "Saint Kitts and Nevis", "st kitts": "Saint Kitts and Nevis", "st kitts and nevis": "Saint Kitts and Nevis",
  "st lucia": "Saint Lucia",
  "sao tome": "Sao Tome and Principe",
  "antigua": "Antigua and Barbuda",
  "holy see": "Vatican City", "vatican": "Vatican City", "vatican city": "Vatican City",
  "palestine": "State of Palestine", "west bank": "State of Palestine",
  "guinea bissau": "Guinea-Bissau",
}
export function normalize(s) {
  return s.toLowerCase().trim().replace(/[-]/g, " ").replace(/[^a-z0-9 ]/g, "").replace(/\s+/g, " ").trim()
}
const COUNTRY_MAP = {}
COUNTRIES.forEach(c => { COUNTRY_MAP[normalize(c.name)] = c.name })
const ALIAS_MAP = {}
Object.entries(COUNTRY_ALIASES).forEach(([k, v]) => { ALIAS_MAP[normalize(k)] = v })
export function resolveCountry(input) {
  const n = normalize(input)
  if (ALIAS_MAP[n]) return ALIAS_MAP[n]
  return COUNTRY_MAP[n] || null
}
export const CONT_COLORS = {
  "Africa": "#F59E0B", "Asia": "#EF4444", "Europe": "#3B82F6",
  "North America": "#10B981", "South America": "#8B5CF6", "Oceania": "#EC4899",
}
export const fmtPop = (n) => n >= 1e9 ? (n/1e9).toFixed(2)+"B" : n >= 1e6 ? (n/1e6).toFixed(1)+"M" : n >= 1e3 ? (n/1e3).toFixed(0)+"K" : String(n)
export const fmtTime = (s) => { const m = Math.floor(s/60); return m+":"+(String(s%60).padStart(2,"0")) }
